FROM ubuntu:14.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y default-jdk


RUN mkdir /env/

WORKDIR /env/

ENTRYPOINT ["export","CLASSPATH=$CLASSPATH:junit-4.10.jar"]